### ISSUE TITLE
Error: Could not resolve metadata for contract at 0x3b63b85894Be00ad6D9FCD977Fa1D60f21dc6dCe  at fetchContractMetadataFromAddress

### ISSUE THREAD

**Issue by PunithNandiraj1** [adrianhajdin/project_crowdfunding#21]
I am getting these errors , Please help 
1.  contract call failure TypeError: Cannot read properties of undefined (reading 'call')
2. Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
3.Error: Could not resolve metadata for contract at 0x3b63b85894Be00ad6D9FCD977Fa1D60f21dc6dCe  at fetchContractMetadataFromAddress

**Comment by croziermaxime** [comment]
Hey, you just use activeChain instead of desiredChainId in you main.jsx file, it worked for me

**Comment by PunithNandiraj1** [comment]
Thank you @croziermaxime
