### ISSUE TITLE
MetaMask notification is not popped up after clicking add a new campaign

### ISSUE THREAD

**Issue by Brijesh-Adeshara** [adrianhajdin/project_crowdfunding#33]
i have tried so many times but i wonder why this happen

**Comment by Brijesh-Adeshara** [comment]
any idea how to resolve this

**Comment by A-Pradeep** [comment]
@Brijesh-Adeshara  Is there any error log on console log on createCampaign trigger ?
Provide error log if any, to understand the issue better.

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep  yes i attached one photo of the error
![WhatsApp Image 2023-04-08 at 5 33 46 PM](https://user-images.githubusercontent.com/127421200/230720117-4aeb74de-9cdf-4cf5-860b-e4aefba86703.jpeg)

**Comment by A-Pradeep** [comment]
@Brijesh-Adeshara  seems `connect` is not working,
can you check with this following code.
https://github.com/adrianhajdin/project_crowdfunding/blob/a554d7eaeefe1f6f2b73c8ecd837b6805aaed4b7/client/src/context/index.jsx#L14

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep Brother i add one line from this line 
import { EditionMetadataWithOwnerOutputSchema } from '@thirdweb-dev/sdk';
but still shows the same error 
attached photo
![error](https://user-images.githubusercontent.com/127421200/230721978-1c1b34f8-4f0f-42d9-8427-838b76217788.jpeg)

**Comment by A-Pradeep** [comment]
On which file have you added ?

**Comment by A-Pradeep** [comment]
@Brijesh-Adeshara  Not sure why it's used for, but on YouTube I've not come across. 
Even added on my local project and not faced any issue. 
Can you remove that line and try once ?

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep yes tried it with and without that line but same error occured
but if i try to create campaign from thirdweb dashboard then it is successfully completed like, from thirdweb dashboard the notification of gas fees is popped up from metamask and i able to add a campaign successfully but from front end it shows this error..

**Comment by A-Pradeep** [comment]
From Thirdweb it will work. 
Seems like your react app not able to trigger the MetaMask. 

1. Can you reinstall the packages once more 
`npm i @thirdweb-dev/react @thirdweb-dev/sdk ethers@^5`
2.  Can you cross check the `main.tsx` so that the `ThirdwebProvider` is at parent level.

For reference 
```
  <ThirdwebProvider activeChain={ChainId.Goerli}>
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider>
```

**Comment by A-Pradeep** [comment]
@Brijesh-Adeshara  It may sound stupid, but make sure the **MetaMask** extension is added on the Browser and you are using the `Goerli test network`

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep yes brother metamask extension is added and i am using goerli test network

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep can you plz provide your CreateCampaign.jsx file ??

**Comment by A-Pradeep** [comment]
Hope this helps
https://gist.github.com/A-Pradeep/10fdc71b7c55db33095b7ad871ddc492

**Comment by Brijesh-Adeshara** [comment]
@A-Pradeep ok thanks..
