### ISSUE TITLE
How can we change the currency or network? 

### ISSUE THREAD

**Issue by gracexnn** [adrianhajdin/project_crowdfunding#46]
Hello i tested this app. It works perfectly fine on goerli, but i changed configs of hardhat and in main.jsx `<ThirdwebProvider desiredChainId={ChainId.Polygon}> `like this. but still doesnt work. Can someone help me please.

**Comment by DoxxSvm** [comment]
You can try this 
`<ThirdwebProvider activeChain="polygon">
      <Component />
    </ThirdwebProvider>`
    
    Make sure you have deployed the contract on Polygon and replaced the correct Contract Address. Also have a look at your default network in hardhat.config.js file

**Comment by gracexnn** [comment]
thank you @DoxxSvm
