### ISSUE TITLE
Fund Campaign error

### ISSUE THREAD

**Issue by lrgcrypto** [adrianhajdin/project_crowdfunding#6]
First of all good job for making this tutorial. 

one issue, regarding funding campaign, if you dont have wallet connected the screen will keep on loaading.

**Comment by gvnut** [comment]
How did you solve this? I see that it also endlessly loads if you do not enter any input into the donation amount on the Campaign details page. Also if you have already donated once it will not prompt your metamask a second time. It will just throw up the loading screen, and you can never donate a second time.
